#!/bin/bash
# vcffilter 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    echo "Value of vcf: '$vcf'"
    echo "Value of info_filter: '${info_filter[@]}'"
    echo "Value of genotype_filter: '${genotype_filter[@]}'"
    echo "Value of advanced_options: '$advanced_options'"

    vcfname=$(dx describe "$vcf" --name)

    filters=""
    
    for filter in "${info_filter[@]}"; do
        filters="$filters -f '$filter'"
    done

    for filter in "${genotype_filter[@]}"; do
        filters="$filters -g '$filter'"
    done

    case $(dx describe "$vcf" --name) in
    *.gz ) 
            prog="gunzip -c"
            vcfname=${vcfname%.gz}
            ;;
    *)
            prog="tee /dev/null"
            ;;
    esac
    vcfname=${vcfname%.vcf}

    cmd="dx cat '$vcf' | $prog | vcffilter $filters $advanced_options | bgzip -c | dx upload -o '${vcfname}.filtered.vcf.gz' --brief -"
    echo "$cmd"
    dx-jobutil-add-output filtered_vcfgz $(bash -c "$cmd") --class=file
}
