#!/bin/bash
# vcfQCrpt 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    set -x

    dx download "$vcfgz" -o /input.vcf.gz
    vcfname=$(dx describe --name "$vcfgz")
    vcfname=${vcfname%.vcf.gz}

    if [ -z "$Rlibs" ]; then
        R --no-save --quiet < /vcfQCrpt/libs.R
        tar -C / -cf /vcfQCrpt.Rlibs.tar /usr/local/lib/R/site-library
        gzip /vcfQCrpt.Rlibs.tar
        output_Rlibs=$(dx upload /vcfQCrpt.Rlibs.tar.gz --brief)
        dx-jobutil-add-output Rlibs "$output_Rlibs" --class=file
    else
        dx download "$Rlibs" -o /vcfQCrpt.Rlibs.tar.gz
        tar -C / -zxf /vcfQCrpt.Rlibs.tar.gz
    fi

    R --no-save --quiet < /vcfQCrpt/generate.R

    html_report=$(dx upload vcfQCrpt.html --destination "${vcfname}.vcfQCrpt.html" --brief)

    dx-jobutil-add-output html_report "$html_report" --class=file
}
